config/routes.rb
Centlog::Application.routes.draw do

  resources :alerts

  resources :transactions

  resources :groups
  
  devise_for :users
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]
  
  
  resources :users, :only => [:index, :show]

  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',   :to => 'pages#about'

  match '/mygroups',   :to => 'groups#mygroups'

  root :to => 'pages#home'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => 'groups_users'

  attr_accessible :name, :description, :owner_id

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true
  validates :owner_id, :presence => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authenticate_user!
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups
  # GET /groups.xml
  def mygroups
    @groups = Group.find(:all, :conditions => {:owner_id => current_user.id})
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    if params[:leave]
      if @group.users.include?(current_user)
      @group.users.delete(current_user)
      end
    end

    if params[:join]
      unless @group.users.include?(current_user)
      @group.users << current_user
      end
    end

    @members =  @group.users.where('id <> ?', @group.owner_id)

    if params[:new_user_email]
      new_member = User.find(:first, :conditions => ['email = ?', params[:new_user_email] ])
      if new_member
      @group.users << new_member
      redirect_to(@group, :notice => 'Member ' + params[:new_user_email] + ' added successfully')
      return
      else
      redirect_to(@group, :notice => 'Member ' + params[:new_user_email]  + ' not found')
      return
      end
    end

    @user_ids = Array.new
    @group.users.each do |u|
      @user_ids << u.id
    end
    @user_ids <<  @group.owner_id

    @transactions = Transaction.scoped(:conditions => ["user_id IN (?)", @user_ids ] )

    @total = @transactions.sum('amount')

    @transactions_paginated = @transactions.paginate(:page => params[:page], :per_page => 20)

    @pie_data = Hash.new
    User.all.each do |u|
      @pie_data[u.email] = u.transactions.sum('amount')
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end

  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end

  protected

  def find_post
    @post = current_user.posts.find(params[:id])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
<% if @group.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
	<ul>
		<% @group.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :name %>
	<br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :description %>
	<br />
	<%= f.text_field :description %>
</div>
<div class="field">
	<%#= f.label :owner_id %>
	<br />
	<%= f.hidden_field :owner_id,  :value => current_user.id %>
</div>
<div class="actions">
	<%= f.submit "Done",:class => "btn primary medium"%>
</div>
<% end %> 

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<table class="zebra-striped">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Owner</th>
	</tr>
	<% @groups.each do |group| %>
	<tr>
		<td> <%= link_to group.name, group %>
		<% if current_user.id == group.owner_id %>
		<%= link_to '(Edit)', edit_group_path(group) %>
		<% end %> </td>
		<td><%= link_to group.description, group %></td>
		<td><%= User.find(group.owner_id).email %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'Create a group', new_group_path,:class => "btn primary medium" %> 

app/views/groups/mygroups.html.erb
<h1>My Groups</h1>
<table class="zebra-striped">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Owner</th>
	</tr>
	<% @groups.each do |group| %>
	<tr>
		<td> <%= link_to group.name, group %>
		<% if current_user.id == group.owner_id %>
		<%= link_to '(Edit)', edit_group_path(group) %>
		<% end %> </td>
		<td><%= link_to group.description, group %></td>
		<td><%= group.owner_id %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'New Group', new_group_path, :class => "btn primary medium" %> 

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="row show-grid">
	<div class="span6">
		<h1> <%= @group.name %> </h1>
	</div>
	<div class="span10">
		<% if current_user.id == @group.owner_id %>

		<%= link_to 'Edit this group', edit_group_path(@group) %>
		<%= link_to 'Delete this group', @group, :confirm => 'Are you sure? This cannot be undone', :method => :delete %>

		<%else%>

		<% if @group.users.include?(current_user) %>

		<%= form_tag @group, :method => 'post' do %>
		<%= hidden_field_tag(:leave, current_user.id) %>
		<%= submit_tag "Leave this group", :name => nil, :class => "btn primary medium" %>
		<% end %>

		<%else%>

		<%= form_tag @group, :method => 'get' do %>
		<%= hidden_field_tag(:join, current_user.id) %>
		<%= submit_tag "Join this group", :name => nil, :class => "btn primary medium" %>
		<% end %>

		<%end%>

		<% end %>
	</div>
</div>
<div class="row show-grid">
	<div class="span12">
		<p>
			<b>Description:</b>
			<%= @group.description %>
		</p>
		<p>
			<b>Owner:</b>
			<% if current_user.id == @group.owner_id %>
			You are the owner of this group!
			<%else%>
			<%= User.find(@group.owner_id).email %>
			<% end %>
			<br/>
		</p>
	</div>
	<div class="span4">
		<h4> Members: </h4>
		<ol>
			<% @members.each do |member| %>
			<li>
				<%= member.email %>
			</li>
			<% end %>
		</ol>
	</div>
</div>
<% if current_user.id == @group.owner_id %> <h4>Add a member</h4>
<%= form_tag @group, :method => 'get' do %>
<%= email_field_tag :new_user_email, params[:new_user_email] %>
<%= submit_tag "Add", :name => nil, :class => "btn primary small" %>
<% end %>
<% end %>
<hr/>
<h3>This Group's expenses<small> Showing <%= @transactions.size%> expenses from <%= pluralize(@members.size + 1 , 'member') %> <small></h3>
<h4> Total expenditure : <%= number_to_currency(@total, :unit => "$") %></h4>
<br/>
<div class="row show-grid">
	<div class="span16">
		<script >
			$(document).ready(function() {
				$("#expense_table").tablesorter({
					sortList : [[3, 1]]
				});
			});

		</script>
		<table class="zebra-striped" id="expense_table">
			<thead>
				<tr>
					<th>Member</th>
					<th>Description</th>
					<th>Amount</th>
					<th>Date</th>
					<th>Location</th>
					<th>Tag</th>
				</tr>
			</thead>
			<tbody>
				<% @transactions_paginated.each do |transaction| %>
				<tr>
					<td><%= User.find(transaction.user_id).email %></td>
					<td><%= link_to transaction.description, transaction %> </td>
					<td><%= link_to number_to_currency(transaction.amount, :unit => "$"), transaction %></td>
					<td><%= transaction.date %></td>
					<td><%= transaction.location %></td>
					<td><%= transaction.tag %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= will_paginate @transactions_paginated %>
	</div>
</div>
<script type="text/javascript" charset="utf-8">
		Highcharts.theme = {
	colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee",
	"#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
	chart: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 400],
	stops: [
	[0, 'rgb(96, 96, 96)'],
	[1, 'rgb(16, 16, 16)']
	]
	},
	borderWidth: 0,
	borderRadius: 15,
	plotBackgroundColor: null,
	plotShadow: false,
	plotBorderWidth: 0
	},
	title: {
	style: {
	color: '#FFF',
	font: '16px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	},
	subtitle: {
	style: {
	color: '#DDD',
	font: '12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	},
	xAxis: {
	gridLineWidth: 0,
	lineColor: '#999',
	tickColor: '#999',
	labels: {
	style: {
	color: '#999',
	fontWeight: 'bold'
	}
	},
	title: {
	style: {
	color: '#AAA',
	font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	}
	},
	yAxis: {
	alternateGridColor: null,
	minorTickInterval: null,
	gridLineColor: 'rgba(255, 255, 255, .1)',
	lineWidth: 0,
	tickWidth: 0,
	labels: {
	style: {
	color: '#999',
	fontWeight: 'bold'
	}
	},
	title: {
	style: {
	color: '#AAA',
	font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	}
	},
	legend: {
	itemStyle: {
	color: '#CCC'
	},
	itemHoverStyle: {
	color: '#FFF'
	},
	itemHiddenStyle: {
	color: '#333'
	}
	},
	labels: {
	style: {
	color: '#CCC'
	}
	},
	tooltip: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 50],
	stops: [
	[0, 'rgba(96, 96, 96, .8)'],
	[1, 'rgba(16, 16, 16, .8)']
	]
	},
	borderWidth: 0,
	style: {
	color: '#FFF'
	}
	},

	plotOptions: {
	line: {
	dataLabels: {
	color: '#CCC'
	},
	marker: {
	lineColor: '#333'
	}
	},
	spline: {
	marker: {
	lineColor: '#333'
	}
	},
	scatter: {
	marker: {
	lineColor: '#333'
	}
	},
	candlestick: {
	lineColor: 'white'
	}
	},

	toolbar: {
	itemStyle: {
	color: '#CCC'
	}
	},

	navigation: {
	buttonOptions: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#606060'],
	[0.6, '#333333']
	]
	},
	borderColor: '#000000',
	symbolStroke: '#C0C0C0',
	hoverSymbolStroke: '#FFFFFF'
	}
	},

	exporting: {
	buttons: {
	exportButton: {
	symbolFill: '#55BE3B'
	},
	printButton: {
	symbolFill: '#7797BE'
	}
	}
	},

	// scroll charts
	rangeSelector: {
	buttonTheme: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	stroke: '#000000',
	style: {
	color: '#CCC',
	fontWeight: 'bold'
	},
	states: {
	hover: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#BBB'],
	[0.6, '#888']
	]
	},
	stroke: '#000000',
	style: {
	color: 'white'
	}
	},
	select: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.1, '#000'],
	[0.3, '#333']
	]
	},
	stroke: '#000000',
	style: {
	color: 'yellow'
	}
	}
	}
	},
	inputStyle: {
	backgroundColor: '#333',
	color: 'silver'
	},
	labelStyle: {
	color: 'silver'
	}
	},

	navigator: {
	handles: {
	backgroundColor: '#666',
	borderColor: '#AAA'
	},
	outlineColor: '#CCC',
	maskFill: 'rgba(16, 16, 16, 0.5)',
	series: {
	color: '#7798BF',
	lineColor: '#A6C7ED'
	}
	},

	scrollbar: {
	barBackgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	barBorderColor: '#CCC',
	buttonArrowColor: '#CCC',
	buttonBackgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	buttonBorderColor: '#CCC',
	rifleColor: '#FFF',
	trackBackgroundColor: {
	linearGradient: [0, 0, 0, 10],
	stops: [
	[0, '#000'],
	[1, '#333']
	]
	},
	trackBorderColor: '#666'
	},

	// special colors for some of the demo examples
	legendBackgroundColor: 'rgba(48, 48, 48, 0.8)',
	legendBackgroundColorSolid: 'rgb(70, 70, 70)',
	dataLabelsColor: '#444',
	textColor: '#E0E0E0',
	maskColor: 'rgba(255,255,255,0.3)'
	};

	// Apply the theme
	var highchartsOptions = Highcharts.setOptions(Highcharts.theme);

	var chart;
	$(document).ready(function() {
	chart = new Highcharts.Chart({
	chart: {
	renderTo: 'expense_pie',
	plotBackgroundColor: null,
	plotBorderWidth: null,
	plotShadow: false
	},
	title: {
	text: 'Expense - Total:<%= number_to_currency(@total, :unit => "$") %>'
	},
	tooltip: {
	formatter: function() {
	return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
	}
	},
	plotOptions: {
	pie: {
	allowPointSelect: true,
	cursor: 'pointer',
	dataLabels: {
	enabled: true,
	color: Highcharts.theme.textColor || '#000000',
	connectorColor: Highcharts.theme.textColor || '#000000',
	formatter: function() {
	return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
	}
	}
	}
	},
	series: [{
	type: 'pie',
	name: 'Expense',
	data:  [
	<% @pie_data.each do |d|%><%= raw d %>,<%end%>
		]
		}]
		});
		});
</script>
<div id="expense_pie" style="width: 800px; height: 600px; padding-top:10px;
padding-bottom:10px;
padding-right:25px;
padding-left:25px;"></div>

<script>
	$(function() {
		var availableTags = [
		<%User.all.each do |u|%>
		"<%=u.email%>",
		<%end%>	
		];
		$( "#new_user_email" ).autocomplete({
			source: availableTags
		});
	});
</script>