config/routes.rb
Centlog::Application.routes.draw do

  resources :alerts

  resources :transactions

  resources :groups
  
  devise_for :users
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]
  
  
  resources :users, :only => [:index, :show]

  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',   :to => 'pages#about'

  match '/mygroups',   :to => 'groups#mygroups'

  root :to => 'pages#home'

end

app/views/shared/_feed.html.erb
<% unless  current_user.feed.empty? %> 
<b>Transaction status feed:</b>
<table class="transactions" summary="User transactions">
	<%= render :partial => 'shared/feed_item', :collection =>  current_user.feed%>
</table>
<% end %> 

app/views/shared/_feed_item.html.erb
<tr>
  <td class="transaction">
  	<% if !current_user?(feed_item.user) %>
    <div>
       <b><%= link_to feed_item.user.first_name, feed_item.user %></b><br /> 
    </div>  
    Spent <%= feed_item.amount %> at <%= feed_item.location %> on <%= feed_item.tag %><br	 />
    <span class="timestamp">
      <i>Expense incurred <%= time_ago_in_words(feed_item.created_at) %> ago.</i>
    </span>
     <% end %>
  </td>
</tr>

app/views/shared/_footer.html.erb
<footer>

	<p>
				Centlog
	</p>	
	<%= debug(params) if Rails.env.development? %>
</footer>

app/views/shared/_header.html.erb
<head>
	<title>Centlog</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "highcharts" %>
	<%= javascript_include_tag "highstock" %>
	<%= javascript_include_tag "slide" %>
	<%= javascript_include_tag "bootstrap-tabs" %>
	<%= javascript_include_tag "bootstrap-alerts" %>
	<%= javascript_include_tag "jquery.tablesorter.min" %>
	
	<%= include_gritter %>


	<%= csrf_meta_tag %>
	<meta charset="utf-8">
	<title>CentLog - your one stop expense tracker</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!-- Le styles -->
	<style type="text/css">
		body {
			padding-top: 60px;
		}
	</style>
	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
</head>

app/views/shared/_notice_messages.html.erb
<% if notice.present? -%>
<p class="alert-message block-message success">
	<a class="close" href="">×</a>
	<%= notice %>
</p>
<% end -%>

<% if alert.present? -%>
<p class="alert-message block-message warning" >
	<a class="close" href="">×</a>
	<%= alert %>
</p>
<% end -%>
<%= gflash %>

app/views/shared/_side_bar.html.erb
<% if user_signed_in? %>
<div class="sidebar">
	<div class="well">
		<h5>Groups</h5>
		<ul>
			<li>
				<a href="/groups">All groups</a>
			</li>
			<li>
				<a href="/mygroups">My groups</a>
			</li>
			<li>
				<a href="/groups/new">Create a new group</a>
			</li>
		</ul>
		<h5>Expenses</h5>
		<ul>
			<li>
				<a href="/transactions">My expenses</a>
			</li>
			<li>
				<a href="/transactions/new">Add a new expense</a>
			</li>
		</ul>
		<h5>Alert</h5>
		<ul>
			<li>
				<a href="/alerts">All alerts</a>
			</li>
			<li>
				<a href="/alerts/new">Add an alert</a>
			</li>
		</ul>
		<h5>Members</h5>
		<ul>
			<li>
				<a href="/users">List members</a>
			</li>
		</ul>
		
	</div>
</div>
<%else%>
<div class="sidebar" style="padding-top:100px;
		padding-bottom:10px;
		padding-right:25px;">
	<div class="well">
		<h5>Who we are</h5>
		<ul>
			<li>
				<a href="/about">About</a>
			</li>
			<li>
				<a href="/contact">Contact</a>
			</li>
		</ul>
		<h5>Start here</h5>
		<ul>
			<li>
				<a href="<%=new_user_session_path%>">Login</a>
			</li>
			<li>
				<a href="<%=new_user_registration_path%>">Register</a>
			</li>
		</ul>
	</div>
</div>
<%end%> 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_topbar.html.erb
<div class="topbar">
	<div class="topbar-inner">
		<div class="container-fluid">
			<a class="brand" href="/">CentLog</a>
			<ul class="nav">
				<li class="active">
					<a href="/">Home</a>
				</li>
				<li>
					<a href="/about">About</a>
				</li>
				<li>
					<a href="/contact">Contact</a>
				</li>
			</ul>
			<ul class="secondary-nav">
				
				<li class="menu">
					<%= render 'devise/menu/registration_items' %>
					<%= render 'devise/menu/login_items' %>
					<br/>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <span class="transactions">
      You have <%= pluralize(current_user.transactions.count, "transaction") %> 
    </span>
  </a>
</div>