config/routes.rb
Centlog::Application.routes.draw do

  resources :alerts

  resources :transactions

  resources :groups
  
  devise_for :users
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]
  
  
  resources :users, :only => [:index, :show]

  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',   :to => 'pages#about'

  match '/mygroups',   :to => 'groups#mygroups'

  root :to => 'pages#home'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :user

  validates :title, :presence => true
  validates :amount, :presence => true
  validates :date, :presence => true
  validates :user_id, :presence => true
  validates_numericality_of :amount, :only_integer => false, :message => "should be valid number."
  
end

app/controllers/alerts_controller.rb
require 'will_paginate/array'

class AlertsController < ApplicationController

  before_filter :authenticate_user!
  # GET /alerts
  # GET /alerts.xml
  def index
    @alerts = current_user.alerts

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alerts }
    end
  end

  # GET /alerts/1
  # GET /alerts/1.xml
  def show
    @alert = Alert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/new
  # GET /alerts/new.xml
  def new
    @alert = Alert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/1/edit
  def edit
    @alert = Alert.find(params[:id])
  end

  # POST /alerts
  # POST /alerts.xml
  def create
    @alert = Alert.new(params[:alert])

    respond_to do |format|
      if @alert.save
        format.html { redirect_to(@alert, :notice => 'Alert was successfully created.') }
        format.xml  { render :xml => @alert, :status => :created, :location => @alert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alerts/1
  # PUT /alerts/1.xml
  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to(@alert, :notice => 'Alert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.xml
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to(alerts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
<% if @alert.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>
	<ul>
		<% @alert.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<br />
	<%= f.hidden_field :user_id,  :value => current_user.id %>
</div>
<div class="field">
	<%= f.label :title %>
	<br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :amount %>
	<br />
	<%= f.text_field :amount %>
</div>
<div class="field">
	<%= f.label :date %>
	<br />
	<%= f.date_select :date %>
</div>
<div class="actions">
	<%= f.submit "Done", :class => "btn primary medium" %>
</div>
<% end %> 

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h2>Manage your alerts <small> Add new alerts, edit or remove existing alerts</small></h2>
<table id="alert_table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Amount</th>
			<th>Date</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @alerts.each do |alert| %>
		<tr>
			<td><%= link_to alert.title, alert %>(<%= link_to 'Edit', edit_alert_path(alert) %>)</td>
			<td><%= link_to alert.amount, alert %></td>
			<td><%= link_to alert.date, alert %></td>
			<td><%= link_to 'Remove alert', alert, :method => :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<br />
<%= link_to 'Add an alert', new_alert_path, :class => "btn primary medium"  %> 

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @alert.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @alert.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @alert.date %>
</p>


<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>