config/routes.rb
Centlog::Application.routes.draw do

  resources :alerts

  resources :transactions

  resources :groups
  
  devise_for :users
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]
  
  
  resources :users, :only => [:index, :show]

  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',   :to => 'pages#about'

  match '/mygroups',   :to => 'groups#mygroups'

  root :to => 'pages#home'

end

app/controllers/transactions_controller.rb
require 'will_paginate/array'



class TransactionsController < ApplicationController

  before_filter :authenticate_user!
  # GET /transactions
  # GET /transactions.xml
  def index

    @transactions = current_user.transactions(:order => "date DESC")

    @sub_title = "Showing all your expenses"

    if params[:search]
      @transactions = @transactions.scoped(:conditions => ['description LIKE ? OR tag LIKE ? OR location LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%"])
    @sub_title = "Found "
    @sub_title << @transactions.size.to_s
    @sub_title << " results matching with - '"
    @sub_title << params[:search]
    @sub_title << "'"
    end

    @total = @transactions.sum('amount')

    #Code below is for calculating information for the Pie chart
    tag_set = Set.new

    @transactions.each do |tran|
      tag_set << tran.tag
    end

    @pie_data = Hash.new

    tag_set.each do |tag|
      temp_trans = @transactions.where("tag = ?", tag)
      @pie_data[tag] = temp_trans.sum('amount')
    end

    #Code below is for calculating information for the Pie chart
    @transactions = @transactions.sort! { |a,b| a.date <=> b.date }

    @graph_data = Hash.new

    @transactions.each do |t|
      time = Time.parse(t.date.to_s).utc.to_i*1000
      if  @graph_data[time]
      @graph_data[time] += t.amount
      else
      @graph_data[time] = t.amount
      end
    end

    #Code below is for calculating information for the bar chart
    @bar_data = Hash.new { |h,v| h[v]= Hash.new }

    @transactions.each do |t|
      trans_tag = t.tag
      month = t.date.strftime("%B, %Y")
      if @bar_data[trans_tag]
        if @bar_data[trans_tag][month]
        @bar_data[trans_tag][month] += t.amount
        else
        @bar_data[trans_tag][month] = t.amount
        end
      else
      @bar_data[trans_tag] = Hash.new
      @bar_data[trans_tag][month] = t.amount
      end
    end

    @months_set = Set.new

    @transactions.each do |t|
      @months_set << t.date.strftime("%B, %Y")
    end

    @transactions_paginated = @transactions.paginate(:page => params[:page], :per_page => 50)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    @transactions = current_user.transactions
    #Code below is for calculating information for the Pie chart
    @tag_set = Set.new

    @transactions.each do |tran|
      @tag_set << tran.tag
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])

    @transactions = current_user.transactions
    #Code below is for calculating information for the Pie chart
    @tag_set = Set.new

    @transactions.each do |tran|
      @tag_set << tran.tag
    end

  end

  # POST /transactions
  # POST /transactions.xml
  def create

    @transaction  = current_user.transactions.build(params[:transaction])

    #@transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
<% if @transaction.errors.any? %>
<br/>
<div id="error_explanation">
	<h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
	<ul>
		<% @transaction.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<br />
	<%= f.hidden_field :user_id,  :value => current_user.id %>
</div>
<div class="field">
	<%= f.label :description %>
	<br />
	<%= f.text_field :description %>
</div>
<div class="field">
	<%= f.label :amount %>
	<br />
	<%= f.text_field :amount %>
</div>
<div class="field">
	<%= f.label :tag %>
	<br />
	<%= f.text_field :tag %>
</div>
<div class="field">
	<%= f.label :location %>
	<br />
	<%= f.text_field :location %>
</div>
<div class="field">
	<%= f.label :date %>
	<br />
	<%= f.date_select :date %>
</div>
<div class="actions">
	<%= f.submit "Done",:class => "btn primary medium"%>
</div>
<% end %> 



<script>
	$(function() {
		var availableTags = [
		<%@tag_set.each do |t|%>
		"<%=t%>",
		<%end%>
		"Gadgets",
		"Food",
		"House",
		"Clothing",
		"Misc",
		"Transport",
		"Insurance",
		"Gifts",
		"Phone",
		"Internet/Cable TV"		
		];
		
		$( "#transaction_tag" ).autocomplete({
			source: availableTags
		});
	});
</script>

app/views/transactions/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<% form_tag transactions_path, :method => 'get' do %>
<p>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search an expense", :name => nil, :class => "btn primary medium"  %>
</p>
<% end %>

<br/>
<br/>
<h2>Your expenditure details<small>  <%= @sub_title%></small></h2>
<h4> Total expenditure : <%= number_to_currency(@total, :unit => "$") %></h4>
<br/>

<%if @transactions.empty? %>
 
No expense tracked! Add a new expense and start tracking your expenditure now.

<%else%>

<script >
$(document).ready(function() 
    { 
        $("#expense_table").tablesorter( {sortList: [[2,1]]} ); 
    } 
); 
</script>
<table class="zebra-striped" id="expense_table">
	<thead>
		<tr>
			<th>Description</th>
			<th>Amount</th>
			<th>Date</th>
			<th>Location</th>
			<th>Tag</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @transactions_paginated.each do |transaction| %>
		<tr>
			<td><%= link_to transaction.description, transaction %> (<%= link_to 'Edit', edit_transaction_path(transaction) %>)</td>
			<td><%= link_to number_to_currency(transaction.amount, :unit => "$"), transaction %></td>
			<td><%= transaction.date %></td>
			<td><%= transaction.location %></td>
			<td><%= transaction.tag %></td>
			<td><%= link_to 'Delete', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate @transactions_paginated %>

<br />
<script type="text/javascript" charset="utf-8">
		Highcharts.theme = {
	colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee",
	"#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
	chart: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 400],
	stops: [
	[0, 'rgb(96, 96, 96)'],
	[1, 'rgb(16, 16, 16)']
	]
	},
	borderWidth: 0,
	borderRadius: 15,
	plotBackgroundColor: null,
	plotShadow: false,
	plotBorderWidth: 0
	},
	title: {
	style: {
	color: '#FFF',
	font: '16px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	},
	subtitle: {
	style: {
	color: '#DDD',
	font: '12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	},
	xAxis: {
	gridLineWidth: 0,
	lineColor: '#999',
	tickColor: '#999',
	labels: {
	style: {
	color: '#999',
	fontWeight: 'bold'
	}
	},
	title: {
	style: {
	color: '#AAA',
	font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	}
	},
	yAxis: {
	alternateGridColor: null,
	minorTickInterval: null,
	gridLineColor: 'rgba(255, 255, 255, .1)',
	lineWidth: 0,
	tickWidth: 0,
	labels: {
	style: {
	color: '#999',
	fontWeight: 'bold'
	}
	},
	title: {
	style: {
	color: '#AAA',
	font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
	}
	}
	},
	legend: {
	itemStyle: {
	color: '#CCC'
	},
	itemHoverStyle: {
	color: '#FFF'
	},
	itemHiddenStyle: {
	color: '#333'
	}
	},
	labels: {
	style: {
	color: '#CCC'
	}
	},
	tooltip: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 50],
	stops: [
	[0, 'rgba(96, 96, 96, .8)'],
	[1, 'rgba(16, 16, 16, .8)']
	]
	},
	borderWidth: 0,
	style: {
	color: '#FFF'
	}
	},

	plotOptions: {
	line: {
	dataLabels: {
	color: '#CCC'
	},
	marker: {
	lineColor: '#333'
	}
	},
	spline: {
	marker: {
	lineColor: '#333'
	}
	},
	scatter: {
	marker: {
	lineColor: '#333'
	}
	},
	candlestick: {
	lineColor: 'white'
	}
	},

	toolbar: {
	itemStyle: {
	color: '#CCC'
	}
	},

	navigation: {
	buttonOptions: {
	backgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#606060'],
	[0.6, '#333333']
	]
	},
	borderColor: '#000000',
	symbolStroke: '#C0C0C0',
	hoverSymbolStroke: '#FFFFFF'
	}
	},

	exporting: {
	buttons: {
	exportButton: {
	symbolFill: '#55BE3B'
	},
	printButton: {
	symbolFill: '#7797BE'
	}
	}
	},

	// scroll charts
	rangeSelector: {
	buttonTheme: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	stroke: '#000000',
	style: {
	color: '#CCC',
	fontWeight: 'bold'
	},
	states: {
	hover: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#BBB'],
	[0.6, '#888']
	]
	},
	stroke: '#000000',
	style: {
	color: 'white'
	}
	},
	select: {
	fill: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.1, '#000'],
	[0.3, '#333']
	]
	},
	stroke: '#000000',
	style: {
	color: 'yellow'
	}
	}
	}
	},
	inputStyle: {
	backgroundColor: '#333',
	color: 'silver'
	},
	labelStyle: {
	color: 'silver'
	}
	},

	navigator: {
	handles: {
	backgroundColor: '#666',
	borderColor: '#AAA'
	},
	outlineColor: '#CCC',
	maskFill: 'rgba(16, 16, 16, 0.5)',
	series: {
	color: '#7798BF',
	lineColor: '#A6C7ED'
	}
	},

	scrollbar: {
	barBackgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	barBorderColor: '#CCC',
	buttonArrowColor: '#CCC',
	buttonBackgroundColor: {
	linearGradient: [0, 0, 0, 20],
	stops: [
	[0.4, '#888'],
	[0.6, '#555']
	]
	},
	buttonBorderColor: '#CCC',
	rifleColor: '#FFF',
	trackBackgroundColor: {
	linearGradient: [0, 0, 0, 10],
	stops: [
	[0, '#000'],
	[1, '#333']
	]
	},
	trackBorderColor: '#666'
	},

	// special colors for some of the demo examples
	legendBackgroundColor: 'rgba(48, 48, 48, 0.8)',
	legendBackgroundColorSolid: 'rgb(70, 70, 70)',
	dataLabelsColor: '#444',
	textColor: '#E0E0E0',
	maskColor: 'rgba(255,255,255,0.3)'
	};

	// Apply the theme
	var highchartsOptions = Highcharts.setOptions(Highcharts.theme);

	var chart;
	$(document).ready(function() {
	chart = new Highcharts.Chart({
	chart: {
	renderTo: 'expense_pie',
	plotBackgroundColor: null,
	plotBorderWidth: null,
	plotShadow: false
	},
	title: {
	text: 'Expense - Total:<%= number_to_currency(@total, :unit => "$") %>'
	},
	tooltip: {
	formatter: function() {
	return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage)  +' %';
	}
	},
	plotOptions: {
	pie: {
	allowPointSelect: true,
	cursor: 'pointer',
	dataLabels: {
	enabled: true,
	color: Highcharts.theme.textColor || '#000000',
	connectorColor: Highcharts.theme.textColor || '#000000',
	formatter: function() {
	return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage)  +' %';
	}
	}
	}
	},
	series: [{
	type: 'pie',
	name: 'Expense',
	data:  [
	<% @pie_data.each do |d|%><%= raw d %>,<%end%>
		]
		}]
		});
		});
</script>
<script type="text/javascript">

	var usdeur = [<% @graph_data.each do |key, value| %>
	[<%= key%>,<%= value%>],<%end%>
	];
	jQuery(function() {// Create the chart
		window.chart = new Highcharts.StockChart({
			chart : {
				renderTo : 'expense_graph'
			},

			rangeSelector : {

				inputEnabled : true,
				selected : 2,
				buttons : [{
					type : 'month',
					count : 6,
					text : '6m'
				}, {
					type : 'year',
					count : 1,
					text : '1y'
				}, {
					type : 'all',
					text : 'All'
				}]
			},

			title : {
				text : 'Day-to-day expenses'
			},

			xAxis : {
				maxZoom : 30 * 24 * 3600000 // fourteen days
			},
			yAxis : {
				title : {
					text : 'US $'
				}
			},

			series : [{
				name : 'US $',
				data : usdeur
			}]
		});
	});

</script>

<script>
var chart;
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'expense_bar',
         defaultSeriesType: 'bar'
      },
      title: {
         text: 'Stacked bar chart'
      },
      xAxis: {
         categories: [
         <%@months_set.each do |m|%>
         '<%= m%>',
         <%end%>
         ]
      },
      yAxis: {
         min: 0,
         title: {
            text: 'Month-wise expenditure'
         }
      },
      legend: {
         backgroundColor: Highcharts.theme.legendBackgroundColorSolid || '#FFFFFF',
         reversed: true
      },
      tooltip: {
         formatter: function() {
            return ''+
                this.series.name +': '+ this.y +'';
         }
      },
      plotOptions: {
         series: {
            stacking: 'normal'
         }
      },
           series: [
           
           <%@bar_data.each do |key,value|%>
           {
           	name: '<%= key%>',
           	data: [  	
           	<%@months_set.each do |m|%>
           	<%if value[m]%>
         	<%=value[m]%>,
         	<%else%>
         	0,
         	<%end%>
         	<%end%>
           	]
           },
           <%end%>
		]
   });
   
   
});
</script>

<ul class="tabs">
	<li class="active">
		<a href="#pie">Expense Division Pie</a>
	</li>
	<li>
		<a href="#bar">Month-wise Bar</a>
	</li>
	<li>
		<a href="#graph">Day-To-Day Graph</a>
	</li>
</ul>
<div class="pill-content">
	<div class="active" id="pie">
		<div id="expense_pie" style="width: 800px; height: 600px; padding-top:10px;
		padding-bottom:10px;
		padding-right:25px;
		padding-left:25px;"></div>
	</div>
	<div id="bar">
		<div id="expense_bar" style="width: 800px; height: 600px;padding-top:10px;
		padding-bottom:10px;
		padding-right:25px;
		padding-left:25px;"></div>
	</div>	
	<div id="graph">
		<div id="expense_graph" style="width: 800px; height: 600px;padding-top:10px;
		padding-bottom:10px;
		padding-right:25px;
		padding-left:25px;"></div>
	</div>
</div>
<script>
	$(function() {
		$('.tabs').tabs()
	})
</script>


<%end%>

<br/>
<br/>
<%= link_to 'Add a new expense', new_transaction_path,:class => "btn primary medium"  %>

app/views/transactions/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<h2><%= @transaction.description %><small><% if current_user.id == @transaction.user_id %> (<%= link_to 'Edit expense', edit_transaction_path(@transaction) %>) <%end%> <small></h2> 
<h4 style="color:#007513;"><%= number_to_currency(@transaction.amount, :unit => "$") %></h4>
<br/>
<p>
	<b>Date:</b>
	<%= @transaction.date %>
</p>
<p>
	<b>Location:</b>
	<%= @transaction.location %>
</p>
<p>
	<b>Tag:</b>
	<%= @transaction.tag %>
</p>

<%= link_to 'My expenses', transactions_path %>